### ISSUE TITLE
allowDisablingButtons

### ISSUE THREAD

**Issue by scannie67** [finity69x2/cover-position-preset-row#22]
This option is not working. 
Buttons aren't disabled.

**Comment by scannie67** [comment]
Hereby my settings a example.
Buttons are still working.

type: custom:cover-position-preset-row
entity: cover.kelder_rolluik_onder
name: Kelder onder
customSetpoints: true
allowDisablingButtons: true
OpenPosition: 100
MidOpenPosition: 50
MidClosePosition: 1
ClosePosition: 0
customText: true
customOpenText: open
customMidOpenText: zon
customMidClosedText: vent
customClosedText: dicht

**Comment by finity69x2** [comment]
> This option is not working.

I'm not sure what you mean by this.

the buttons are disabled by default (option set to true) if the cover is in the position set by the button.

to prevent the buttons being disabled you need to set the option to false. Since the option is defaulted to true your config doesn't change anything that would be different if you had just left it out.

all "allow disabling buttons" do is allow you to try to hit the button again and have it call the service again if the card thinks the cover is already in the correct position.
